title: "Button"
description: |
  Buttons should be used in situations where a dramatic, obvious action is required.

patterns:
  basic:
    title: "Main Button"
    description: |
      Default to using the main button.
    width: "12em"
    fields:
      - name: button_text
        type: string
        example: "Our Oils"
        required: false
      - name: button_url
        type: url
        example: "/products/"
        required: false
  cart:
    title: "Cart Button"
    description: |
      Link to cart page.
  extra:
    title: "Extra Button"
    description: |
      Use this incase another button can't be used.
    fields:
      - name: text
        type: string
        example: "Buy Now"
        required: false
      - name: url
        type: url
        example: "#"
        required: false
  nav:
    title: "Nav Button"
    description: |
      Use for navigation in the header/footer.
    background: "--color-accent-light"
    fields:
      - name: text
        type: string
        example: "Buy Now"
        required: false
      - name: url
        type: url
        example: "#"
        required: false
