title: "Form"
description: |
  Forms are used for documenting information in the necessary text fiellds during checkout or subscribing to a mailing list.

patterns:
  data-list:
    title: "Data list"
    description: |
      Used for selecting category from a list.
  date-picker:
    title: "Date Picker"
    description: |
      Can be used to select year, month, day and time.
  main-form:
    title: "Main Form"
    description: |
      Default for field setting.
    fields:
      - name: for
        type: string
        example: "email"
      - name: header
        type: string
        example: "Email"
      - name: type
        type: string
        example: "email"
      - name: placeholder
        type: string
        example: "please type email"
      - name: id
        type: string
        example: "email"
  number-picker:
    title: "Number Picker"
    description: |
      Select quantity of items to add to cart.
  radio-button:
    title: "Radio Button"
    description: |
      Selecting shipping method.
    fields:
      - name: text
        type: string
        example: "Sign up for subscription."
  text:
    title: "Text"
    description: |
      Default for text-area setting.
    fields:
      - name: text
        type: string
        example: "Tell us about yourself."
